begin;
select plan(22);
insert into public.user_roles(user_id,role) values ('60000000-0000-0000-0000-000000000001','admin'),('60000000-0000-0000-0000-000000000002','editor');
set local request.jwt.claim.sub='60000000-0000-0000-0000-000000000001'; set local role authenticated;
select lives_ok($$select public.save_archive_record('song',null,'pgtap-admin-song','Admin song','2026-08-11','2026-08-12','description','','https://example.com/admin-song','Official song','official',false)$$,'admin saves a song draft');
select is((select status from public.songs where slug='pgtap-admin-song'),'draft','song starts as draft');
select lives_ok(format($$select public.save_archive_record('song',%s,'pgtap-admin-song','Admin song','2026-08-11','2026-08-12','description','','https://example.com/admin-song','Official song','official',true)$$,(select song_id from public.songs where slug='pgtap-admin-song')),'admin publishes a song');
select is((select verification_status from public.song_sources where song_id=(select song_id from public.songs where slug='pgtap-admin-song')),'verified','published song source is verified');
select lives_ok(format($$select public.save_archive_record('song',%s,'pgtap-admin-song-renamed','Admin song','2026-08-11','2026-08-12','description','','https://example.com/admin-song','Official song','official',true)$$,(select song_id from public.songs where slug='pgtap-admin-song')),'admin updates a song slug');
select is((select slug from public.songs where title='Admin song'),'pgtap-admin-song-renamed','song slug is updated');
select lives_ok(format($$select public.save_archive_record_with_event('song',%s,'pgtap-admin-song-renamed','Admin song','2026-08-11','2026-08-12','description','','https://example.com/admin-song','Official song','official',true,%s)$$,(select song_id from public.songs where slug='pgtap-admin-song-renamed'),(select min(event_id) from public.events)),'admin atomically relates a song to its first-performance event');
select is((select event_id from public.song_events where song_id=(select song_id from public.songs where title='Admin song')),(select min(event_id) from public.events),'song event relation is saved');
select lives_ok(format($$select public.save_archive_record('song',%s,'pgtap-admin-song','Admin song',null,'2026-08-12','description','','https://example.com/admin-song','Official song','official',false)$$,(select song_id from public.songs where title='Admin song')),'admin clears an unconfirmed first-performance date');
select is((select count(*) from public.timeline_occurrences where song_id=(select song_id from public.songs where title='Admin song')),0::bigint,'clearing the date removes the timeline occurrence');
select lives_ok($$select public.save_archive_record('costume',null,'pgtap-admin-costume','Admin costume','2026-08-11',null,'description','','https://example.com/admin-costume','Official costume','official',true)$$,'admin publishes a costume');
select is((select status from public.costumes where slug='pgtap-admin-costume'),'published','costume is published');
select lives_ok(format($$select public.update_source_state(%s,'unavailable','https://web.archive.org/example')$$,(select source_id from public.sources where url='https://example.com/admin-costume')),'admin records an unavailable source and archive URL');
select is((select availability_status from public.sources where url='https://example.com/admin-costume'),'unavailable','source availability is saved');
select lives_ok($$select public.create_milestone_draft('pgtap-discard-draft','Discard me','test','','2026-08-11',true,'https://example.com/discard','Discard source','official')$$,'admin creates a draft to discard');
select lives_ok(format($$select public.discard_milestone_draft(%s,'duplicate')$$,(select milestone_id from public.milestones where slug='pgtap-discard-draft')),'admin discards a draft with a reason');
select is((select count(*) from public.milestones where slug='pgtap-discard-draft'),0::bigint,'discard removes the draft');
select lives_ok($$select public.create_milestone_draft('pgtap-revise-published','Before revision','test','','2026-08-11',true,'https://example.com/revise-before','Before revision source','official')$$,'admin creates a milestone to revise');
select lives_ok(format($$select public.confirm_and_publish_milestone(%s)$$,(select milestone_id from public.milestones where slug='pgtap-revise-published')),'admin publishes the milestone to revise');
select lives_ok(format($$select public.revise_published_milestone(%s,'After revision','test','corrected','2026-08-12',true,'https://example.com/revise-after','After revision source','official','corrected date')$$,(select milestone_id from public.milestones where slug='pgtap-revise-published')),'admin revises a published milestone with a reason');
select is((select title from public.milestones where slug='pgtap-revise-published'),'After revision','published revision updates the fact in place');
reset role; set local request.jwt.claim.sub='60000000-0000-0000-0000-000000000002'; set local role authenticated;
select throws_ok($$select public.save_archive_record('song',null,'forbidden-song','Forbidden',current_date,null,'','','https://example.com/forbidden-song','Forbidden','web',false)$$,'42501',null,'editor cannot use solo admin archive workflow');
reset role; select * from finish(); rollback;
