create table if not exists public.songs (
  song_id bigint generated by default as identity primary key,
  title text not null,
  release_date date,
  first_performed_date date,
  description text,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.song_sources (
  source_id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs(song_id) on delete cascade,
  label text not null,
  url text not null,
  accessed_on date not null default current_date
);

create table if not exists public.song_events (
  song_id bigint not null references public.songs(song_id) on delete cascade,
  event_id integer not null references public.events(event_id) on delete cascade,
  relation_type text not null default 'related' check (relation_type in ('first_performance', 'release', 'related')),
  primary key (song_id, event_id, relation_type)
);

create table if not exists public.costumes (
  costume_id bigint generated by default as identity primary key,
  name text not null,
  debut_date date,
  description text,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.costume_sources (
  source_id bigint generated by default as identity primary key,
  costume_id bigint not null references public.costumes(costume_id) on delete cascade,
  label text not null,
  url text not null,
  accessed_on date not null default current_date
);

create table if not exists public.costume_events (
  costume_id bigint not null references public.costumes(costume_id) on delete cascade,
  event_id integer not null references public.events(event_id) on delete cascade,
  relation_type text not null default 'worn_at' check (relation_type in ('debut', 'worn_at', 'related')),
  primary key (costume_id, event_id, relation_type)
);

alter table public.songs enable row level security;
alter table public.song_sources enable row level security;
alter table public.song_events enable row level security;
alter table public.costumes enable row level security;
alter table public.costume_sources enable row level security;
alter table public.costume_events enable row level security;

create policy "songs are publicly readable" on public.songs for select using (true);
create policy "song sources are publicly readable" on public.song_sources for select using (true);
create policy "song events are publicly readable" on public.song_events for select using (true);
create policy "costumes are publicly readable" on public.costumes for select using (true);
create policy "costume sources are publicly readable" on public.costume_sources for select using (true);
create policy "costume events are publicly readable" on public.costume_events for select using (true);

do $$
declare
  miraibaru_song_id bigint;
  miraibaru_costume_id bigint;
begin
  if not exists (select 1 from public.songs where title = 'ミライバルダンス') then
    insert into public.songs (title, first_performed_date, description)
    values ('ミライバルダンス', '2022-01-10', '4人体制初のワンマンライブ第1部で初披露されたことが、登録済みイベント情報に記録されています。')
    returning song_id into miraibaru_song_id;

    insert into public.song_sources (song_id, label, url, accessed_on)
    values (miraibaru_song_id, 'わーすたアーカイブ 登録済みイベント情報', '/events/118', '2026-08-11');

    if exists (select 1 from public.events where event_id = 118) then
      insert into public.song_events (song_id, event_id, relation_type)
      values (miraibaru_song_id, 118, 'first_performance');
    end if;
  end if;

  if not exists (select 1 from public.costumes where name = 'ミライバルダンス衣装') then
    insert into public.costumes (name, debut_date, description)
    values ('ミライバルダンス衣装', '2022-03-26', '7周年ライブの公式グッズで「ミライバルダンス衣装ver.」という衣装名が確認できます。')
    returning costume_id into miraibaru_costume_id;

    insert into public.costume_sources (costume_id, label, url, accessed_on)
    values (miraibaru_costume_id, 'わーすた公式グッズ', 'https://wa-suta.world/goods/items.php?id=1001982', '2026-08-11');
  end if;
end $$;
