-- First editorial workflow vertical: milestones must transition through RPCs.

create table public.archive_audit_log (
  audit_id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  action text not null,
  from_status text,
  to_status text,
  actor_id uuid not null,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.archive_audit_log enable row level security;

create policy archive_audit_log_select_reviewer
  on public.archive_audit_log for select to authenticated
  using (public.has_role_at_least('reviewer'));

drop policy if exists milestones_write_editor on public.milestones;
drop policy if exists occurrences_write_editor on public.timeline_occurrences;

create policy milestones_select_editor
  on public.milestones for select to authenticated
  using (public.has_role_at_least('viewer'));

create policy milestones_insert_draft_editor
  on public.milestones for insert to authenticated
  with check (
    public.has_role_at_least('editor')
    and status = 'draft'
  );

create policy milestones_update_draft_editor
  on public.milestones for update to authenticated
  using (
    public.has_role_at_least('editor')
    and status = 'draft'
  )
  with check (
    public.has_role_at_least('editor')
    and status = 'draft'
  );

create policy milestones_delete_draft_editor
  on public.milestones for delete to authenticated
  using (
    public.has_role_at_least('editor')
    and status = 'draft'
  );

create policy occurrences_select_editor
  on public.timeline_occurrences for select to authenticated
  using (public.has_role_at_least('viewer'));

create policy occurrences_insert_draft_editor
  on public.timeline_occurrences for insert to authenticated
  with check (
    public.has_role_at_least('editor')
    and status = 'draft'
  );

create policy occurrences_update_draft_editor
  on public.timeline_occurrences for update to authenticated
  using (
    public.has_role_at_least('editor')
    and status = 'draft'
  )
  with check (
    public.has_role_at_least('editor')
    and status = 'draft'
  );

create policy occurrences_delete_draft_editor
  on public.timeline_occurrences for delete to authenticated
  using (
    public.has_role_at_least('editor')
    and status = 'draft'
  );

create or replace function public.submit_milestone_for_review(
  milestone_to_submit bigint
)
returns public.milestones
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  submitted public.milestones;
begin
  if not public.has_role_at_least('editor') then
    raise exception 'editor role required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.milestone_sources
    where milestone_id = milestone_to_submit
  ) then
    raise exception 'at least one milestone source is required' using errcode = '23514';
  end if;

  update public.milestones
  set status = 'review', updated_at = now()
  where milestone_id = milestone_to_submit
    and status = 'draft'
  returning * into submitted;

  if submitted.milestone_id is null then
    raise exception 'milestone must be in draft status' using errcode = '22023';
  end if;

  insert into public.archive_audit_log (
    entity_type, entity_id, action, from_status, to_status, actor_id
  )
  values (
    'milestone', submitted.milestone_id, 'submit_for_review', 'draft', 'review', auth.uid()
  );

  return submitted;
end;
$$;

create or replace function public.publish_milestone(
  milestone_to_publish bigint
)
returns public.milestones
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  published public.milestones;
begin
  if not public.has_role_at_least('reviewer') then
    raise exception 'reviewer role required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.milestone_sources
    where milestone_id = milestone_to_publish
      and fact_kind = 'title'
      and verification_status = 'verified'
  ) then
    raise exception 'verified milestone title source is required' using errcode = '23514';
  end if;

  if not exists (
    select 1
    from public.timeline_occurrences occurrence
    join public.occurrence_sources occurrence_source
      on occurrence_source.occurrence_id = occurrence.occurrence_id
    where occurrence.milestone_id = milestone_to_publish
      and occurrence.status in ('draft', 'review')
      and occurrence.occurred_on is not null
      and occurrence_source.fact_kind = 'occurred_on'
      and occurrence_source.verification_status = 'verified'
  ) then
    raise exception 'verified milestone occurrence date is required' using errcode = '23514';
  end if;

  update public.milestones
  set status = 'published', updated_at = now()
  where milestone_id = milestone_to_publish
    and status = 'review'
  returning * into published;

  if published.milestone_id is null then
    raise exception 'milestone must be in review status' using errcode = '22023';
  end if;

  update public.timeline_occurrences
  set status = 'published', updated_at = now()
  where milestone_id = milestone_to_publish
    and status in ('draft', 'review');

  insert into public.archive_audit_log (
    entity_type, entity_id, action, from_status, to_status, actor_id
  )
  values (
    'milestone', published.milestone_id, 'publish', 'review', 'published', auth.uid()
  );

  return published;
end;
$$;

create or replace function public.withdraw_milestone(
  milestone_to_withdraw bigint,
  withdrawal_reason text
)
returns public.milestones
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  withdrawn public.milestones;
begin
  if not public.has_role_at_least('reviewer') then
    raise exception 'reviewer role required' using errcode = '42501';
  end if;

  if nullif(btrim(withdrawal_reason), '') is null then
    raise exception 'withdrawal reason is required' using errcode = '22023';
  end if;

  update public.milestones
  set status = 'withdrawn', updated_at = now()
  where milestone_id = milestone_to_withdraw
    and status = 'published'
  returning * into withdrawn;

  if withdrawn.milestone_id is null then
    raise exception 'milestone must be in published status' using errcode = '22023';
  end if;

  update public.timeline_occurrences
  set status = 'withdrawn', updated_at = now()
  where milestone_id = milestone_to_withdraw
    and status = 'published';

  insert into public.archive_audit_log (
    entity_type, entity_id, action, from_status, to_status, actor_id, reason
  )
  values (
    'milestone', withdrawn.milestone_id, 'withdraw', 'published', 'withdrawn', auth.uid(), btrim(withdrawal_reason)
  );

  return withdrawn;
end;
$$;

revoke all on function public.submit_milestone_for_review(bigint) from public;
revoke all on function public.publish_milestone(bigint) from public;
revoke all on function public.withdraw_milestone(bigint, text) from public;

grant execute on function public.submit_milestone_for_review(bigint) to authenticated;
grant execute on function public.publish_milestone(bigint) to authenticated;
grant execute on function public.withdraw_milestone(bigint, text) to authenticated;
