-- Archive provenance foundation. This migration only adds schema and preserves
-- the existing events, songs, costumes, and public URLs.

alter table public.user_roles
  drop constraint if exists user_roles_role_check;

alter table public.user_roles
  add constraint user_roles_role_check
  check (role in ('viewer', 'editor', 'reviewer', 'admin'));

create or replace function public.has_role_at_least(required_role text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (
      select case role
        when 'viewer' then 10
        when 'editor' then 20
        when 'reviewer' then 30
        when 'admin' then 40
        else 0
      end
      from public.user_roles
      where user_id = auth.uid()
    ),
    0
  ) >= case required_role
    when 'viewer' then 10
    when 'editor' then 20
    when 'reviewer' then 30
    when 'admin' then 40
    else 100
  end;
$$;

create table public.sources (
  source_id bigint generated by default as identity primary key,
  url text not null unique,
  title text not null,
  publisher text,
  published_on date,
  accessed_at timestamptz not null default now(),
  archived_url text,
  source_kind text not null default 'web'
    check (source_kind in ('official', 'web', 'video', 'social', 'book', 'internal')),
  availability_status text not null default 'unchecked'
    check (availability_status in ('unchecked', 'available', 'suspect', 'unavailable')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.members (
  member_id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null unique,
  name_kana text,
  color text,
  joined_on date,
  left_on date,
  profile_source_id bigint references public.sources(source_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (left_on is null or joined_on is null or left_on >= joined_on)
);

create table public.milestones (
  milestone_id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null,
  kind text not null,
  description text,
  status text not null default 'draft'
    check (status in ('draft', 'review', 'published', 'withdrawn')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.songs
  add column if not exists slug text,
  add column if not exists status text not null default 'published';

alter table public.songs
  add constraint songs_slug_format_check
    check (slug is null or slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  add constraint songs_status_check
    check (status in ('draft', 'review', 'published', 'withdrawn'));

create unique index songs_slug_unique
  on public.songs(slug)
  where slug is not null;

alter table public.costumes
  add column if not exists slug text,
  add column if not exists status text not null default 'published';

alter table public.costumes
  add constraint costumes_slug_format_check
    check (slug is null or slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  add constraint costumes_status_check
    check (status in ('draft', 'review', 'published', 'withdrawn'));

create unique index costumes_slug_unique
  on public.costumes(slug)
  where slug is not null;

alter table public.song_sources
  add column if not exists canonical_source_id bigint references public.sources(source_id) on delete restrict,
  add column if not exists fact_kind text not null default 'title',
  add column if not exists verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'verified', 'rejected')),
  add column if not exists verified_by uuid,
  add column if not exists verified_at timestamptz,
  add column if not exists note text;

alter table public.costume_sources
  add column if not exists canonical_source_id bigint references public.sources(source_id) on delete restrict,
  add column if not exists fact_kind text not null default 'name',
  add column if not exists verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'verified', 'rejected')),
  add column if not exists verified_by uuid,
  add column if not exists verified_at timestamptz,
  add column if not exists note text;

create table public.event_sources (
  event_id integer not null references public.events(event_id) on delete restrict,
  source_id bigint not null references public.sources(source_id) on delete restrict,
  fact_kind text not null,
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'verified', 'rejected')),
  verified_by uuid,
  verified_at timestamptz,
  note text,
  primary key (event_id, source_id, fact_kind)
);

create table public.milestone_sources (
  milestone_id bigint not null references public.milestones(milestone_id) on delete restrict,
  source_id bigint not null references public.sources(source_id) on delete restrict,
  fact_kind text not null,
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'verified', 'rejected')),
  verified_by uuid,
  verified_at timestamptz,
  note text,
  primary key (milestone_id, source_id, fact_kind)
);

create table public.event_members (
  event_id integer not null references public.events(event_id) on delete restrict,
  member_id bigint not null references public.members(member_id) on delete restrict,
  relation_kind text not null default 'appearance',
  primary key (event_id, member_id, relation_kind)
);

create table public.song_members (
  song_id bigint not null references public.songs(song_id) on delete restrict,
  member_id bigint not null references public.members(member_id) on delete restrict,
  relation_kind text not null default 'performer',
  primary key (song_id, member_id, relation_kind)
);

create table public.costume_members (
  costume_id bigint not null references public.costumes(costume_id) on delete restrict,
  member_id bigint not null references public.members(member_id) on delete restrict,
  variant_note text not null default '',
  primary key (costume_id, member_id, variant_note)
);

create table public.milestone_members (
  milestone_id bigint not null references public.milestones(milestone_id) on delete restrict,
  member_id bigint not null references public.members(member_id) on delete restrict,
  primary key (milestone_id, member_id)
);

create table public.milestone_events (
  milestone_id bigint not null references public.milestones(milestone_id) on delete restrict,
  event_id integer not null references public.events(event_id) on delete restrict,
  primary key (milestone_id, event_id)
);

create table public.timeline_occurrences (
  occurrence_id bigint generated by default as identity primary key,
  occurrence_kind text not null
    check (occurrence_kind in ('event', 'first_performance', 'release', 'costume_debut', 'video', 'milestone')),
  occurred_on date,
  date_precision text not null default 'day'
    check (date_precision in ('day', 'month', 'year', 'unknown')),
  is_group_wide boolean not null default false,
  status text not null default 'draft'
    check (status in ('draft', 'review', 'published', 'withdrawn')),
  event_id integer references public.events(event_id) on delete restrict,
  song_id bigint references public.songs(song_id) on delete restrict,
  costume_id bigint references public.costumes(costume_id) on delete restrict,
  youtube_link_id integer references public.youtube_links(youtube_link_id) on delete restrict,
  milestone_id bigint references public.milestones(milestone_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (num_nonnulls(event_id, song_id, costume_id, youtube_link_id, milestone_id) = 1),
  check ((date_precision = 'unknown') = (occurred_on is null))
);

create table public.occurrence_members (
  occurrence_id bigint not null references public.timeline_occurrences(occurrence_id) on delete restrict,
  member_id bigint not null references public.members(member_id) on delete restrict,
  primary key (occurrence_id, member_id)
);

create table public.occurrence_sources (
  occurrence_id bigint not null references public.timeline_occurrences(occurrence_id) on delete restrict,
  source_id bigint not null references public.sources(source_id) on delete restrict,
  fact_kind text not null,
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'verified', 'rejected')),
  verified_by uuid,
  verified_at timestamptz,
  note text,
  primary key (occurrence_id, source_id, fact_kind)
);

create index timeline_occurrences_date_idx
  on public.timeline_occurrences(occurred_on desc, occurrence_kind, occurrence_id);
create index timeline_occurrences_event_idx on public.timeline_occurrences(event_id) where event_id is not null;
create index timeline_occurrences_song_idx on public.timeline_occurrences(song_id) where song_id is not null;
create index timeline_occurrences_costume_idx on public.timeline_occurrences(costume_id) where costume_id is not null;
create index timeline_occurrences_video_idx on public.timeline_occurrences(youtube_link_id) where youtube_link_id is not null;
create index timeline_occurrences_milestone_idx on public.timeline_occurrences(milestone_id) where milestone_id is not null;

alter table public.sources enable row level security;
alter table public.members enable row level security;
alter table public.milestones enable row level security;
alter table public.event_sources enable row level security;
alter table public.milestone_sources enable row level security;
alter table public.event_members enable row level security;
alter table public.song_members enable row level security;
alter table public.costume_members enable row level security;
alter table public.milestone_members enable row level security;
alter table public.milestone_events enable row level security;
alter table public.timeline_occurrences enable row level security;
alter table public.occurrence_members enable row level security;
alter table public.occurrence_sources enable row level security;

create policy sources_select_public on public.sources for select to public using (true);
create policy members_select_public on public.members for select to public using (true);
create policy milestones_select_published on public.milestones for select to public using (status = 'published');
create policy event_sources_select_verified on public.event_sources for select to public using (verification_status = 'verified');
create policy milestone_sources_select_verified on public.milestone_sources for select to public using (verification_status = 'verified');
create policy event_members_select_public on public.event_members for select to public using (true);
create policy song_members_select_public on public.song_members for select to public using (true);
create policy costume_members_select_public on public.costume_members for select to public using (true);
create policy milestone_members_select_public on public.milestone_members for select to public using (true);
create policy milestone_events_select_public on public.milestone_events for select to public using (true);
create policy occurrences_select_published on public.timeline_occurrences for select to public using (status = 'published');
create policy occurrence_members_select_public on public.occurrence_members for select to public using (true);
create policy occurrence_sources_select_verified on public.occurrence_sources for select to public using (verification_status = 'verified');

create policy sources_write_editor on public.sources for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy members_write_reviewer on public.members for all to authenticated
  using (public.has_role_at_least('reviewer')) with check (public.has_role_at_least('reviewer'));
create policy milestones_write_editor on public.milestones for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy event_sources_write_editor on public.event_sources for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy milestone_sources_write_editor on public.milestone_sources for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy event_members_write_editor on public.event_members for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy song_members_write_editor on public.song_members for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy costume_members_write_editor on public.costume_members for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy milestone_members_write_editor on public.milestone_members for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy milestone_events_write_editor on public.milestone_events for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy occurrences_write_editor on public.timeline_occurrences for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy occurrence_members_write_editor on public.occurrence_members for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));
create policy occurrence_sources_write_editor on public.occurrence_sources for all to authenticated
  using (public.has_role_at_least('editor')) with check (public.has_role_at_least('editor'));

insert into public.members (slug, name, name_kana, color, joined_on)
values
  ('nanase-hirokawa', '廣川奈々聖', 'ひろかわ ななせ', '#8fd8ef', '2015-03-29'),
  ('miri-matsuda', '松田美里', 'まつだ みり', '#b99bd9', '2015-03-29'),
  ('ririka-kodama', '小玉梨々華', 'こだま りりか', '#f5b3cb', '2015-03-29'),
  ('ruka-mishina', '三品瑠香', 'みしな るか', '#f2d35f', '2015-03-29')
on conflict (slug) do nothing;

insert into public.sources (url, title, source_kind, availability_status, accessed_at)
select distinct url, label, 'internal', 'available', accessed_on::timestamptz
from public.song_sources
on conflict (url) do update set
  title = excluded.title,
  accessed_at = greatest(public.sources.accessed_at, excluded.accessed_at);

insert into public.sources (url, title, source_kind, availability_status, accessed_at)
select distinct url, label,
  case when url like 'https://wa-suta.world/%' then 'official' else 'web' end,
  'available',
  accessed_on::timestamptz
from public.costume_sources
on conflict (url) do update set
  title = excluded.title,
  accessed_at = greatest(public.sources.accessed_at, excluded.accessed_at);

update public.song_sources ss
set canonical_source_id = s.source_id,
    verification_status = 'verified',
    verified_at = coalesce(ss.verified_at, ss.accessed_on::timestamptz),
    fact_kind = case
      when exists (
        select 1 from public.songs song
        where song.song_id = ss.song_id and song.first_performed_date is not null
      ) then 'first_performed_date'
      else 'title'
    end
from public.sources s
where s.url = ss.url and ss.canonical_source_id is null;

update public.costume_sources cs
set canonical_source_id = s.source_id,
    verification_status = 'verified',
    verified_at = coalesce(cs.verified_at, cs.accessed_on::timestamptz),
    fact_kind = case
      when exists (
        select 1 from public.costumes costume
        where costume.costume_id = cs.costume_id and costume.debut_date is not null
      ) then 'debut_date'
      else 'name'
    end
from public.sources s
where s.url = cs.url and cs.canonical_source_id is null;

insert into public.timeline_occurrences (
  occurrence_kind, occurred_on, date_precision, is_group_wide, status, song_id
)
select 'first_performance', first_performed_date, 'day', true, 'published', song_id
from public.songs
where first_performed_date is not null
  and not exists (
    select 1 from public.timeline_occurrences occurrence
    where occurrence.song_id = songs.song_id
      and occurrence.occurrence_kind = 'first_performance'
  );

insert into public.timeline_occurrences (
  occurrence_kind, occurred_on, date_precision, is_group_wide, status, song_id
)
select 'release', release_date, 'day', true, 'published', song_id
from public.songs
where release_date is not null
  and not exists (
    select 1 from public.timeline_occurrences occurrence
    where occurrence.song_id = songs.song_id
      and occurrence.occurrence_kind = 'release'
  );

insert into public.timeline_occurrences (
  occurrence_kind, occurred_on, date_precision, is_group_wide, status, costume_id
)
select 'costume_debut', debut_date, 'day', true, 'published', costume_id
from public.costumes
where debut_date is not null
  and not exists (
    select 1 from public.timeline_occurrences occurrence
    where occurrence.costume_id = costumes.costume_id
      and occurrence.occurrence_kind = 'costume_debut'
  );

insert into public.occurrence_sources (
  occurrence_id, source_id, fact_kind, verification_status, verified_at
)
select occurrence.occurrence_id, ss.canonical_source_id, ss.fact_kind, 'verified', ss.verified_at
from public.timeline_occurrences occurrence
join public.song_sources ss on ss.song_id = occurrence.song_id
where ss.canonical_source_id is not null
on conflict do nothing;

insert into public.occurrence_sources (
  occurrence_id, source_id, fact_kind, verification_status, verified_at
)
select occurrence.occurrence_id, cs.canonical_source_id, cs.fact_kind, 'verified', cs.verified_at
from public.timeline_occurrences occurrence
join public.costume_sources cs on cs.costume_id = occurrence.costume_id
where cs.canonical_source_id is not null
on conflict do nothing;
